sudo: false

language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

php:
  - 7.1
  - 5.3
  - 5.6

env:
  # WordPress latest
  - WP_VERSION=latest
  # WordPress 4.7
  - WP_VERSION=4.7

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.1

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [[ ${TRAVIS_PHP_VERSION:0:2} == "7." ]]; then
      composer global require "phpunit/phpunit=5.7.*"
    else
      composer global require "phpunit/phpunit=4.8.*"
    fi
  - |
    composer global require wp-coding-standards/wpcs
    phpcs --config-set installed_paths $HOME/.composer/vendor/wp-coding-standards/wpcs

script:
  #- phpcs --standard=phpcs.ruleset.xml $(find . -name '*.php')
  - phpunit
