language: php

notifications:
  email:
    on_success: never
    on_failure: change

# Declare versions of PHP to test
php:
  # alias of 7
  - 7.1
  # aliased to a recent 5.6.x version
  - 5.6
  # aliased to a recent 5.5.x version
  - 5.5

# WordPress comes from the Git mirror, where 'master' mirrors svn 'trunk' and
# x.y mirrors the latest from the x.y branch
env:
  # WordPress latest
  - WP_VERSION=latest
  # WordPress 4.7
  - WP_VERSION=4.7

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.1

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION 

script: phpunit
